version: '3'
services:

    apache:
        build:
          context: .
          dockerfile: phpapache.dockerfile
        ports:
          - "8080:80"
        volumes:
          - ./htdocs:/var/www/html
          - ./logs:/var/log
        environment:
          - APACHE_RUN_USER=#1000
          - APACHE_RUN_GROUP=#1000
        depends_on:
          - mysql

    mysql:
      image: mariadb:latest
      environment:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'secret'
          MYSQL_DATABASE: 'db1'
      volumes:
        - ./mysql_data:/var/lib/mysql
      ports:
        - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: secret
        ports:
            - "8081:80"
        depends_on:
            - mysql